### PR TITLE
Add vg v1.44.0 .dist and .min idexes

### PR DESCRIPTION
**Pull request by glennhickey**
@adamnovak pointed out that giraffe indexes made before vg version [1.44.0](https://github.com/vgteam/vg/releases/tag/v1.44.0) are no longer compatible with vg. 

So I re-indexed all the mc graphs using `vg 1.44.0` on the `xg/gbwt` files to create new distance and minimizer indexes.  The new files have `.dist2/.min2` extensions and the old indexes stay where they are, and the table is updated accordingly.  

Note that since [2.3.0](https://github.com/ComparativeGenomicsToolkit/cactus/releases/tag/v2.3.0), minigraph-cactus produces graphs using the latest formats (including gbz).

### CODE REVIEW

**Comment by adamnovak** [comment]
If we want to use `.dist2`/`.min2` extensions, we might want to update Giraffe to check those extensions first when fishing around for indexes based on the graph name.

**Comment by glennhickey** [comment]
Sigh.. I'd always hand-specified them and didn't realize giraffe did that.  Perhaps `.2.dist` / `2.min` ?  Open to any suggestions..

**Comment by adamnovak** [comment]
`.2.dist` won't work any better with the existing code. We still probably want to change it to check the new names too.

**Comment by glennhickey** [comment]
of course.  I guess most people downloading in the future will be using current vg so I'll make sure the new ones have the proper names and move the old ones.  thanks for catching this!

**Pull request merged**
